name: Update GXA metadata

on:
  schedule:
    - cron: '0 0 * * *'     # Runs daily at midnight UTC
  workflow_dispatch:        # Allows manual triggering

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip install requests pandas pyyaml

      - name: run metadata update script
        run: python fetch_gxa_metadata.py gxa-studies

      - name: check for changes
        run: |
          git diff --exit-code || echo "Changes detected"
        id: check_changes
        continue-on-error: true

      - name: commit and push changes
        if: steps.check_changes.outcome == 'failure'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gxa-studies.tsv gxa-studies.yaml
          git commit -m "Update GXA metadata [$(date -u)]"
          git push
