---
name: Validate YAML format and python code

on:
  push: {}
  pull_request: {}

jobs:
  validate:
    name: YAML & python validation
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install prettier and flake8
        run: |
          npm install --save-dev prettier
          pip install flake8

      - name: check YAML syntax
        run: |
          npx prettier --check --log-level error "**/*.yaml"

      - name: lint python code
        run: |
          flake8 --max-line-length=150 .
