---
name: Validate YAML format and python code

on:
  push: {}
  pull_request: {}

jobs:
  validate:
    name: YAML & python validation
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: install yamllint and flake8
        run: |
          pip install yamllint flake8

      - name: check YAML syntax
        run: |
          yamllint .

      - name: lint python code
        run: |
          flake8 --max-line-length=100 .
